/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "counties": {                                    "en": "counties",                                        "de": "Landkreis",                                       "ru": "графств",                                         "pt": "condados",                                        "nl": "provincies",                                      "fr": "comtés",                                          "it": "contee",                                          "es": "condados",                                        "pl": "powiaty",                                         "uk": "Округ",                                           "zh-cn": "县"},
    "federal state": {                               "en": "federal state",                                   "de": "Bundesland",                                      "ru": "федеральное государство",                         "pt": "Estado federal",                                  "nl": "federale staat",                                  "fr": "Etat fédéral",                                    "it": "stato federale",                                  "es": "estado federal",                                  "pl": "federalny stan",                                  "uk": "Штат",                                            "zh-cn": "联邦州"},
    "ignore Public Holidays": {                      "en": "ignore Public Holidays",                          "de": "Feiertage ignorieren",                            "ru": "игнорировать государственные праздники",          "pt": "ignorar Feriados",                                "nl": "negeer feestdagen",                               "fr": "ignorer les jours fériés",                        "it": "ignora i giorni festivi",                         "es": "ignorar los días festivos",                       "pl": "ignoruj święta państwowe",                        "uk": "Ігнорувати свята",                                "zh-cn": "忽略公共假期"},
    "no selection": {                                "en": "no selection",                                    "de": "keine Auswahl",                                   "ru": "нет выбора",                                      "pt": "nenhuma seleção",                                 "nl": "geen selectie",                                   "fr": "pas de choix",                                    "it": "nessuna selezione",                               "es": "Sin selección",                                   "pl": "brak wyboru",                                     "uk": "немає вибору",                                    "zh-cn": "没有选择"},
    "places": {                                      "en": "place",                                           "de": "Ort",                                             "ru": "место",                                           "pt": "Lugar, colocar",                                  "nl": "plaats",                                          "fr": "endroit",                                         "it": "posto",                                           "es": "sitio",                                           "pl": "miejsce",                                         "uk": "Місце",                                           "zh-cn": "地点"},
    "schools": {                                     "en": "school",                                          "de": "Schule",                                          "ru": "школа",                                           "pt": "escola",                                          "nl": "school-",                                         "fr": "école",                                           "it": "scuola",                                          "es": "colegio",                                         "pl": "szkoła",                                          "uk": "Школа",                                           "zh-cn": "学校"},
};